### ISSUE TITLE
Don't give random items unexpectedly

### ISSUE THREAD

**Issue by QinomeD** [Chummycho/Prey_Public#3]
I randomly get Runes of Spellsword, Kensei, and Berserker + the grizzly bear pet, and also the class crate every now and then. Idk if it's intentional, but imo it would be better if they were collectable with quest (checkbox quest available to redeem every x minutes?). Currently it's just very annoying, especially in battle.

**Comment by Chummycho** [comment]
The class lootbox is intentional but I might change it since 50% of people like it and 50% of people don't.

However, getting more subclass runes is definitely NOT intentional. I think it might be a bug introduced in the last update when I changed the main class name from Warlord to Warden. I'll have a look at it and it will be fixed in the update coming in a few days.

I'll also look into better ways to give the class lootbox but there still needs to be something like it because that's how players get the class pets.

**Comment by QinomeD** [comment]
Thanks for the response! I don't have issues with the class lootbox, it's just that it's given automatically, and can clutter your inventory when you're in a fight or smth idk

**Comment by Chummycho** [comment]
I put out a massive update and removed the class lootboxes
